### ISSUE TITLE
init command needs to execute pyre init

### ISSUE THREAD

**Issue by SaurusXI** [angelinag/protecc#17]
Currently the user must do `pyre init` followed by `protecc init` in their source folder.  We should replace this with a single `protecc init` command execution by calling `pyre init` under the hood.

**Comment by Saif807380** [comment]
Is there a specific directory where this command must be run or is it okay if the pyre-configuration file is created inside the config directory?

**Comment by Saif807380** [comment]
Also, do we need to change the default values in the configuration files?

**Comment by SaurusXI** [comment]
Actually all the files going in the project root might be better. Don't think we need a config folder at all.
`pyre init` files definitely need to go in root though
