### ISSUE TITLE
Sanitizer

### ISSUE THREAD

**Issue by gasharova** [angelinag/protecc#6]
Use the sanitizers to sanitize the data. 
Recommended to do it using the general @Sanitize annotation.

**Comment by SaurusXI** [comment]
According to [this](https://pyre-check.org/docs/pysa-basics#sanitizers), needs to inject Sanitize decorators in `.pysa` file in working dir. Best tackled after closing #5

**Comment by gasharova** [comment]
This might be tackled in the future but for now we're not planning to.
